"""remover campo unico nome

Revision ID: 05636af9db55
Revises: 94a16244d93c
Create Date: 2025-10-18 20:31:25.654860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05636af9db55'
down_revision: Union[str, Sequence[str], None] = '94a16244d93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuarios_nome_key', 'usuarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('usuarios_nome_key', 'usuarios', ['nome'])
    # ### end Alembic commands ###
