
services:
  # Banco de dados PostgreSQL compartilhado entre todos os microsserviços
  db:
    image: postgres:15
    container_name: gorgona_db
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  # Microsserviço de autenticação (usuários e login)
  autenticacao:
    build: ./backend/microsservice_user  # Caminho do Dockerfile
    container_name: gorgona_user
    ports:
      - "${MICROSSERVICE_USER_PORT}:8000"  # Porta no host, 8000 no container
    env_file:
      - ./backend/microsservice_user/.env  # Injeta variáveis de ambiente
    volumes:
    - ./backend/microsservice_user/src:/app/src  # <- mapeia código
    - ./backend/microsservice_user/alembic.ini:/app/alembic.ini  # <- mapeia alembic.ini
    - ./backend/microsservice_user/alembic:/app/alembic        # pasta de migrations
    depends_on:
      - db                          # Garante que o DB suba primeiro

# Volumes para persistir dados do banco
volumes:
  db_data:
