
services:
  # Banco de dados PostgreSQL compartilhado entre todos os microsserviços
  database:
    image: postgres:15
    container_name: database
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  # Microsserviço de usuario (usuários e login)
  usuario:
    build: ./backend/microsservice_user  # Caminho do Dockerfile
    container_name: user
    ports:
      - "${MICROSSERVICE_USER_PORT}:8000"  # Porta no host, 8000 no container
    env_file:
      - .env  # Injeta variáveis de ambiente
    volumes:
    - ./backend/microsservice_user/src:/app/src  # <- mapeia código
    - ./backend/microsservice_user/alembic.ini:/app/alembic.ini  # <- mapeia alembic.ini
    - ./backend/microsservice_user/alembic:/app/alembic        # pasta de migrations
    depends_on:
      - database                          # Garante que o DB suba primeiro

# Microsserviço de produto
  produto:
    build: ./backend/microsservice_product
    container_name: product
    ports:
      - "${MICROSSERVICE_PRODUCT_PORT}:8000"
    env_file:
      - .env
    volumes:
    - ./backend/microsservice_product/src:/app/src
    - ./backend/microsservice_product/alembic.ini:/app/alembic.ini
    - ./backend/microsservice_product/alembic:/app/alembic
    depends_on:
      - database
      - usuario

# Volumes para persistir dados do banco
volumes:
  database_data:
